name: Notify on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  notify-server:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trigger pull/deploy script remotely
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} "cd /apps/edusatit && git pull && ./deploy.sh ${{ github.ref_name }}"
